// GENERATED by scripts/compute-csp-hash.mjs — do not edit by hand.
// Regenerated on every build from app/theme-script.ts (§3.4).
//
// GitHub Pages cannot serve custom HTTP headers, so the CSP is delivered via
// <meta http-equiv="Content-Security-Policy"> in <head> (app/layout.tsx).
// Meta-CSP limitations (vs header delivery): frame-ancestors and
// upgrade-insecure-requests are ignored by browsers in meta form; HSTS,
// X-Content-Type-Options, Referrer-Policy, Permissions-Policy and
// X-Frame-Options are header-only and therefore NOT enforceable on GitHub
// Pages. Full analysis: docs/SECURITY_HEADERS.md.

export const CSP_META = "default-src 'self'; script-src 'self' 'sha256-HcvLGA0SfVYNoB0UR7c+WQ+TxZLGSHn+WpmFcpheOqg='; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; form-action 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests";
