/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/wada-theme.ts
 * Command: astryx theme build theme/wada-theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

/**
 * wada theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { wadaTheme } from './wada';
 *   import './wada.css';
 */
export const wadaTheme = {
  name: 'wada',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#b35d15, #e08b4a)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#fffdf7, #051230)",
    "--color-neutral": "light-dark(#231A131A, #EEE0D733)",
    "--color-background-surface": "light-dark(#ffffff, #221e18)",
    "--color-background-body": "light-dark(#faf6ec, #171410)",
    "--color-overlay": "light-dark(#231A1366, #231A1399)",
    "--color-overlay-hover": "light-dark(#231A130D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#231A131A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#f3ecdb, #100e0b)",
    "--color-text-primary": "light-dark(#051230, #ece4d2)",
    "--color-text-secondary": "light-dark(#34454c, #b6bfc1)",
    "--color-text-disabled": "light-dark(#A08D82, #6C5B50)",
    "--color-text-accent": "light-dark(#bd4b41, #e28579)",
    "--color-icon-accent": "light-dark(#bd4b41, #e28579)",
    "--color-icon-primary": "light-dark(#231A13, #EEE0D7)",
    "--color-icon-secondary": "light-dark(#53443A, #BBA79C)",
    "--color-icon-disabled": "light-dark(#A08D82, #6C5B50)",
    "--color-background-card": "light-dark(#ffffff, #221e18)",
    "--color-background-popover": "light-dark(#ffffff, #221e18)",
    "--color-background-inverted": "light-dark(#051230, #0b1226)",
    "--color-border": "light-dark(#e3d9c0, #3a332a)",
    "--color-border-emphasized": "light-dark(#34454c, #b6bfc1)",
    "--color-skeleton": "light-dark(#BBA79C, #53443A)",
    "--color-track": "light-dark(#BBA79C, #53443A)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--radius-none": "0px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--radius-chat": "42px",
    "--radius-full": "9999px",
    "--duration-fast-min": "130ms",
    "--duration-fast": "175ms",
    "--duration-fast-max": "235ms",
    "--duration-medium-min": "310ms",
    "--duration-medium": "410ms",
    "--duration-medium-max": "545ms",
    "--duration-slow-min": "730ms",
    "--duration-slow": "975ms",
    "--duration-slow-max": "1300ms",
    "--font-family-body": "\"Space Mono\", ui-monospace, SFMono-Regular, Menlo, monospace",
    "--font-family-heading": "\"Space Mono\"",
    "--font-family-code": "\"Space Mono\", ui-monospace, monospace",
    "--color-success": "light-dark(#2e6b45, #7db894)",
    "--color-error": "light-dark(#bd4b41, #e8897f)",
    "--color-warning": "light-dark(#8a5f14, #d9b35c)",
    "--focus-outline-color": "light-dark(#8a4a11, #f0a878)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)",
        "fontWeight": "var(--font-weight-bold)"
      },
      ":focus-visible": {
        "outlineWidth": "2px",
        "outlineStyle": "solid",
        "outlineColor": "var(--color-focus-outline-color)",
        "outlineOffset": "2px"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "Space Mono",
        "fallbacks": "ui-monospace, SFMono-Regular, Menlo, monospace"
      },
      "heading": {
        "family": "Space Mono",
        "weight": "bold",
        "weights": {
          "1": "bold",
          "2": "bold",
          "3": "bold"
        }
      },
      "code": {
        "family": "Space Mono",
        "fallbacks": "ui-monospace, monospace"
      }
    },
    "color": {
      "accent": "#b35d15",
      "neutralStyle": "warm",
      "contrast": "standard"
    },
    "radius": {
      "base": 4,
      "multiplier": 1.5
    },
    "motion": {
      "fast": 175,
      "medium": 410,
      "slow": 975,
      "ratio": 0.75
    }
  },

};
