/**
 * Wada theme — Misty Darjeeling Tea. GENERATED by scripts/generate-theme.mjs
 * from scripts/derive-palette.mjs output. Do not edit by hand; edit the
 * derivation script and regenerate.
 *
 * Project-owned defineTheme (no vendor theme package). Colours derive from
 * Sanzo Wada's "A Dictionary of Color Combinations" (1933, public domain):
 * plates #102, #137, #139 — hue preserved, lightness/chroma adjusted for
 * WCAG 2.2 AA. Authored in OKLCH, shipped as hex for StyleX/CSS interop.
 * [light, dark] tuples compile to CSS light-dark().
 */
import {defineTheme} from '@astryxdesign/core/theme';

export const wadaTheme = defineTheme({
  name: 'wada',
  typography: {
    scale: {base: 16, ratio: 1.2},
    body: {family: 'Space Mono', fallbacks: 'ui-monospace, SFMono-Regular, Menlo, monospace'},
    heading: {family: 'Space Mono', weight: 'bold', weights: {1: 'bold', 2: 'bold', 3: 'bold'}},
    code: {family: 'Space Mono', fallbacks: 'ui-monospace, monospace'},
  },
  radius: {base: 4, multiplier: 1.5},
  motion: {fast: 175, medium: 410, slow: 975, ratio: 0.75},
  color: {accent: '#b35d15', neutralStyle: 'warm', contrast: 'standard'},
  tokens: {
    '--color-background-body': ['#faf6ec', '#171410'],
    '--color-background-surface': ['#ffffff', '#221e18'],
    '--color-background-card': ['#ffffff', '#221e18'],
    '--color-background-popover': ['#ffffff', '#221e18'],
    '--color-background-muted': ['#f3ecdb', '#100e0b'],
    '--color-background-inverted': ['#051230', '#0b1226'],
    '--color-text-primary': ['#051230', '#ece4d2'],
    '--color-text-secondary': ['#34454c', '#b6bfc1'],
    '--color-accent': ['#b35d15', '#e08b4a'],
    '--color-on-accent': ['#fffdf7', '#051230'],
    '--color-text-accent': ['#bd4b41', '#e28579'],
    '--color-icon-accent': ['#bd4b41', '#e28579'],
    '--color-border': ['#e3d9c0', '#3a332a'],
    '--color-border-emphasized': ['#34454c', '#b6bfc1'],
    '--color-success': ['#2e6b45', '#7db894'],
    '--color-error': ['#bd4b41', '#e8897f'],
    '--color-warning': ['#8a5f14', '#d9b35c'],
    '--focus-outline-color': ['#8a4a11', '#f0a878'],
  },
  components: {
    button: {
      base: {
        borderRadius: 'var(--radius-full)',
        fontWeight: 'var(--font-weight-bold)',
      },
      ':focus-visible': {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: 'var(--color-focus-outline-color)',
        outlineOffset: '2px',
      },
    },
  },
});
