/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/wada-theme.ts
 * Command: astryx theme build theme/wada-theme.ts
 * CLI: @astryxdesign/cli@0.6.0
 * Core: @astryxdesign/core@0.6.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const wadaTheme: DefinedTheme;
