/**
 * Generates theme/wada-theme.ts (project-owned defineTheme) from the computed
 * palette — values are transcribed by the machine, never re-typed by hand.
 * Also emits the DESIGN_SYSTEM.md token table.
 *
 * Run: node scripts/generate-theme.mjs   (after scripts/derive-palette.mjs)
 */
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {parse, rgb, formatHex, formatCss, oklch} from 'culori';
import {LIGHT, DARK, contrast, nearestWada, toOklch} from './derive-palette.mjs';

const palette = JSON.parse(readFileSync('theme/wada-palette.json', 'utf8'));

/** oklch(...) string -> hex, for the theme module (StyleX/CSS interop). */
const oklchToHex = s => formatHex(rgb(parse(s)));

const tokenEntries = (T, mode) => {
  const hexOf = k => oklchToHex(T[k]);
  const bg = mode === 'light' ? oklchToHex(T['color-surface-page']) : oklchToHex(T['color-surface-page']);
  // [lightValue, darkValue] tuples are compiled to CSS light-dark() by the theme build.
  return [
    ['--color-background-body', hexOf('color-surface-page')],
    ['--color-background-surface', hexOf('color-surface-raised')],
    ['--color-background-card', hexOf('color-surface-raised')],
    ['--color-background-popover', hexOf('color-surface-raised')],
    ['--color-background-muted', mode === 'light' ? hexOf('color-surface-sunken') : hexOf('color-surface-sunken')],
    ['--color-background-inverted', mode === 'light' ? oklchToHex(LIGHT['color-ink-deep']) : oklchToHex(DARK['color-ink-deep'])],
    ['--color-text-primary', hexOf('color-text-primary')],
    ['--color-text-secondary', hexOf('color-text-secondary')],
    ['--color-accent', hexOf('color-action-primary')],
    ['--color-on-accent', hexOf('color-text-on-action')],
    ['--color-text-accent', hexOf('color-accent')],
    ['--color-icon-accent', hexOf('color-accent')],
    ['--color-border', hexOf('color-border-subtle')],
    ['--color-border-emphasized', mode === 'light' ? oklchToHex(T['color-text-secondary']) : okkfix(mode)],
    ['--color-success', hexOf('color-status-success')],
    ['--color-error', hexOf('color-status-error')],
    ['--color-warning', hexOf('color-status-warning')],
    ['--focus-outline-color', hexOf('color-focus-ring')],
  ];
};
// placeholder helper to keep the mapping above honest — dark emphasized border uses Neutral Gray darkened
const okkfix = mode => mode === 'dark' ? oklchToHex(DARK['color-text-secondary']) : oklchToHex(LIGHT['color-text-secondary']);

const mkTuple = pairs => pairs.map(([k, v]) => `    '${k}': ['${v[0]}', '${v[1]}'],`).join('\n');

const lightEntries = tokenEntries(LIGHT, 'light');
const darkEntries = tokenEntries(DARK, 'dark');

// zip by token name: [lightHex, darkHex]
const byName = Object.fromEntries(darkEntries.map(([k, v]) => [k, v]));
const zipped = lightEntries.map(([k, v]) => [k, [v, byName[k]]]);

const themeTs = `/**
 * Wada theme — Misty Darjeeling Tea. GENERATED by scripts/generate-theme.mjs
 * from scripts/derive-palette.mjs output. Do not edit by hand; edit the
 * derivation script and regenerate.
 *
 * Project-owned defineTheme (no vendor theme package). Colours derive from
 * Sanzo Wada's "A Dictionary of Color Combinations" (1933, public domain):
 * plates #102, #137, #139 — hue preserved, lightness/chroma adjusted for
 * WCAG 2.2 AA. Authored in OKLCH, shipped as hex for StyleX/CSS interop.
 * [light, dark] tuples compile to CSS light-dark().
 */
import {defineTheme} from '@astryxdesign/core/theme';

export const wadaTheme = defineTheme({
  name: 'wada',
  typography: {
    scale: {base: 16, ratio: 1.2},
    body: {family: 'Space Mono', fallbacks: 'ui-monospace, SFMono-Regular, Menlo, monospace'},
    heading: {family: 'Space Mono', weight: 'bold', weights: {1: 'bold', 2: 'bold', 3: 'bold'}},
    code: {family: 'Space Mono', fallbacks: 'ui-monospace, monospace'},
  },
  radius: {base: 4, multiplier: 1.5},
  motion: {fast: 175, medium: 410, slow: 975, ratio: 0.75},
  color: {accent: '${oklchToHex(LIGHT['color-action-primary'])}', neutralStyle: 'warm', contrast: 'standard'},
  tokens: {
${mkTuple(zipped)}
  },
  components: {
    button: {
      base: {
        borderRadius: 'var(--radius-full)',
        fontWeight: 'var(--font-weight-bold)',
      },
      ':focus-visible': {
        outlineWidth: '2px',
        outlineStyle: 'solid',
        outlineColor: 'var(--color-focus-outline-color)',
        outlineOffset: '2px',
      },
    },
  },
});
`;

mkdirSync('theme', {recursive: true});
writeFileSync('theme/wada-theme.ts', themeTs);

/* ── DESIGN_SYSTEM.md token table ─────────────────────────────────────── */
const semanticDoc = {
  'color-surface-page': 'Page background',
  'color-surface-raised': 'Cards, popovers, raised UI',
  'color-surface-sunken': 'Wells, code blocks, inset areas',
  'color-text-primary': 'Body and heading text',
  'color-text-secondary': 'Supporting text, captions',
  'color-text-on-action': 'Text on primary action fill',
  'color-border-subtle': 'Hairline borders, dividers',
  'color-action-primary': 'Primary buttons, key CTAs',
  'color-action-primary-hover': 'Primary action hover state',
  'color-accent': 'Accent highlights (Etruscan Red)',
  'color-accent-soft': 'Accent tint background',
  'color-focus-ring': 'Focus indicator (≥3:1 adjacent)',
  'color-status-success': 'Success status text/icons',
  'color-status-warning': 'Warning status text/icons',
  'color-status-error': 'Error status text/icons',
  'color-status-info': 'Informational status text/icons',
};

const wadaNames = {
  'color-surface-page': 'Ivory Buff (#102) — lightness raised',
  'color-surface-raised': 'White (Ivory Buff family)',
  'color-surface-sunken': 'Ivory Buff (#102) — chroma reduced',
  'color-text-primary': 'Deep Indigo (#139)',
  'color-text-secondary': 'Slate Color (#57) family',
  'color-text-on-action': 'Warm white (Ivory Buff family)',
  'color-border-subtle': 'Ivory Buff (#102) — darkened',
  'color-action-primary': 'Orange Rufous (#102)',
  'color-action-primary-hover': 'Orange Rufous (#102) — darkened',
  'color-accent': 'Etruscan Red (#137)',
  'color-accent-soft': 'Etruscan Red (#137) — tint',
  'color-focus-ring': 'Orange Rufous (#102) — darkened',
  'color-status-success': 'Pistachio Green (#137)',
  'color-status-warning': 'Cinnamon Buff (#137) — darkened',
  'color-status-error': 'Etruscan Red (#137)',
  'color-status-info': 'Salvia Blue (#139) / Deep Lyons Blue family',
};

let table = `| Token | Usage | Wada source | Light oklch | Light hex | Dark oklch | Dark hex |\n|---|---|---|---|---|---|---|\n`;
for (const key of Object.keys(semanticDoc)) {
  const l = LIGHT[key];
  const d = DARK[key];
  table += `| \`${key}\` | ${semanticDoc[key]} | ${wadaNames[key]} | \`${l}\` | \`${oklchToHex(l)}\` | \`${d}\` | \`${oklchToHex(d)}\` |\n`;
}

const contrastRows = palette.contrast.map(r => `| ${r.mode} | \`${r.fg}\` | ${r.bg} | ${r.ratio}:1 | ${r.need}:1 | ${r.pass ? 'PASS' : 'FAIL'} |`).join('\n');

const doc = `# Design System — Misty Darjeeling Tea

> GENERATED artifact assembled by \`scripts/generate-theme.mjs\` from the computed
> palette (\`scripts/derive-palette.mjs\`). Numeric values are authoritative in
> \`theme/wada-palette.json\`; this document mirrors them.

## Palette authority — Sanzo Wada

Selected plates from *A Dictionary of Color Combinations* (Sanzo Wada, 1933 — public domain):

| Plate | Colours (official names) | Role |
|---|---|---|
| **#102** | Ivory Buff · Orange Rufous | surfaces (Ivory Buff) + primary action (Orange Rufous) |
| **#137** | Etruscan Red · Cinnamon Buff · Pistachio Green | accent, warning tint, success |
| **#139** | Salvia Blue · Deep Indigo · Neutral Gray | info, primary ink, dark-mode secondary text |

Hex values digitised from public reference digitisations:
- https://sanzo-wada.dmbk.io/ (archive, §0 #5)
- https://wscolors.com/colors (159-colour table: Etruscan Red #c55347, Ivory Buff #ebd3a2, Orange Rufous #c16b27, Pistachio Green #648f7b, Salvia Blue #97acc8, Deep Indigo #051230, Neutral Gray #b6bfc1)
- https://colors.elwyn.co/ (combination index: #102/#137/#139 compositions)

**Provenance note:** the archive serves colour values but no programmatic per-plate
endpoint (assets/data.json → 404, verified). Plate numbers + official names are cited
from the archive/combination indexes above; no images, code, or scans are bundled.

## Derivation rule (§3.2.3)

Hue is **preserved** from the Wada source. Only lightness (OKLCH L) and chroma (C)
are adjusted — automatically, by \`derive-palette.mjs\` — until each documented
text/background pair meets WCAG 2.2 AA in **both** modes. Body text targets ≥7:1.

## Semantic tokens

${table}

## Measured contrast (computed, WCAG-relative-luminance)

| Mode | Foreground | Background | Ratio | Required | Result |
|---|---|---|---|---|---|
${contrastRows}

## Focus & target sizes (§3.5)

- Focus ring: \`color-focus-ring\`, ≥3:1 against adjacent colours in both modes (verified above).
- SC 2.5.8: all interactive targets ≥24×24 CSS px (see ARCHITECTURE.md component notes).
- SC 2.4.11: sticky header must not obscure focused elements — header is non-sticky below
  1024px; on desktop it uses \`scroll-margin-top\` on all anchor targets.

## Dark mode

Single mechanism: blocking inline \`<head>\` script reads \`localStorage.theme\`, falls back to
\`prefers-color-scheme\`, sets \`data-theme\` on \`<html>\` before first paint (§3.3). The
\`[light, dark]\` token tuples compile to CSS \`light-dark()\`, resolved by \`color-scheme\`
which the reset stylesheet binds to \`data-theme\`.

## Token bridge (§3.1) — summary

CSS custom properties are the single source of truth. The project-owned Wada theme
(\`theme/wada-theme.ts\`) defines Astryx's own \`--color-*\` variables via \`defineTheme\`;
\`@astryxdesign/core/tailwind-theme.css\` (vendor bridge) maps Tailwind v4 \`@theme inline\`
utilities onto those same variables. Neither engine hardcodes a colour literal. Full
rationale in \`docs/ARCHITECTURE.md\`.
`;
mkdirSync('docs', {recursive: true});
writeFileSync('docs/DESIGN_SYSTEM.md', doc);
console.log('Wrote theme/wada-theme.ts and docs/DESIGN_SYSTEM.md');
